/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Jul 27 12:01:58 CEST 2005 by MyEclipse Hibernate Tool.
 */
package com.company.vo;

import java.io.Serializable;

/**
 * A class that represents a row in the book table. You can customize the
 * behavior of this class by editing the class, {@link Book()}. WARNING: DO NOT
 * EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse
 * Hibernate tool integration.
 */
public abstract class AbstractBook implements Serializable
{
    /**
     * The cached hash code value for this instance. Settting to 0 triggers
     * re-calculation.
     */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer id;

    /** The value of the customer association. */
    private Customer customer;

    /** The value of the simple title property. */
    private java.lang.String title;

    /** The value of the simple author property. */
    private java.lang.String author;

    /** The value of the simple available property. */
    private java.lang.Boolean available;

    /**
     * Simple constructor of AbstractBook instances.
     */
    public AbstractBook()
    {
    }

    /**
     * Constructor of AbstractBook instances given a simple primary key.
     * 
     * @param id
     */
    public AbstractBook(java.lang.Integer id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * 
     * @param id
     */
    public void setId(java.lang.Integer id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the title column.
     * 
     * @return java.lang.String
     */
    public java.lang.String getTitle()
    {
        return this.title;
    }

    /**
     * Set the value of the title column.
     * 
     * @param title
     */
    public void setTitle(java.lang.String title)
    {
        this.title = title;
    }

    /**
     * Return the value of the author column.
     * 
     * @return java.lang.String
     */
    public java.lang.String getAuthor()
    {
        return this.author;
    }

    /**
     * Set the value of the author column.
     * 
     * @param author
     */
    public void setAuthor(java.lang.String author)
    {
        this.author = author;
    }

    /**
     * Return the value of the customer_fk column.
     * 
     * @return Customer
     */
    public Customer getCustomer()
    {
        return this.customer;
    }

    /**
     * Set the value of the customer_fk column.
     * 
     * @param customer
     */
    public void setCustomer(Customer customer)
    {
        this.customer = customer;
    }

    /**
     * Return the value of the available column.
     * 
     * @return java.lang.Byte
     */
    public java.lang.Boolean getAvailable()
    {
        return this.available;
    }

    /**
     * Set the value of the available column.
     * 
     * @param available
     */
    public void setAvailable(java.lang.Boolean available)
    {
        this.available = available;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the
     * primary key values.
     * 
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (!(rhs instanceof Book))
            return false;
        Book that = (Book) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            if (!this.getId().equals(that.getId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern
     * with the exception of array properties (these are very unlikely primary
     * key types).
     * 
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
