package com.company.vo.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the book table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="book"
 */
public abstract class BaseBook  implements Serializable {

	public static String PROP_AVAILABLE = "available";
	public static String PROP_AUTHOR = "author";
	public static String PROP_CUSTOMER = "customer";
	public static String PROP_TITLE = "title";
	public static String PROP_ID = "id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _title;
	private java.lang.String _author;
	private java.lang.Boolean _available;

	// many to one
	private com.company.vo.Customer _customer;


	// constructors
	public BaseBook () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseBook (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: title
	 */
	public java.lang.String getTitle () {
		return _title;
	}

	/**
	 * Set the value related to the column: title
	 * @param _title the title value
	 */
	public void setTitle (java.lang.String _title) {
		this._title = _title;
	}


	/**
	 * Return the value associated with the column: author
	 */
	public java.lang.String getAuthor () {
		return _author;
	}

	/**
	 * Set the value related to the column: author
	 * @param _author the author value
	 */
	public void setAuthor (java.lang.String _author) {
		this._author = _author;
	}


	/**
	 * Return the value associated with the column: available
	 */
	public java.lang.Boolean isAvailable () {
		return _available;
	}

	/**
	 * Set the value related to the column: available
	 * @param _available the available value
	 */
	public void setAvailable (java.lang.Boolean _available) {
		this._available = _available;
	}


	/**
     * @hibernate.property
     *  column=customer_fk
	 */
	public com.company.vo.Customer getCustomer () {
		return this._customer;
	}

	/**
	 * Set the value related to the column: customer_fk
	 * @param _customer the customer_fk value
	 */
	public void setCustomer (com.company.vo.Customer _customer) {
		this._customer = _customer;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.company.vo.base.BaseBook)) return false;
		else {
			com.company.vo.base.BaseBook mObj = (com.company.vo.base.BaseBook) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}