package com.company.vo.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the customer table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="customer"
 */
public abstract class BaseCustomer  implements Serializable {

	public static String PROP_LASTNAME = "lastname";
	public static String PROP_NAME = "name";
	public static String PROP_AGE = "age";
	public static String PROP_ID = "id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _name;
	private java.lang.String _lastname;
	private java.lang.Integer _age;

	// collections
	private java.util.Collection _books;


	// constructors
	public BaseCustomer () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCustomer (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: name
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: name
	 * @param _name the name value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: lastname
	 */
	public java.lang.String getLastname () {
		return _lastname;
	}

	/**
	 * Set the value related to the column: lastname
	 * @param _lastname the lastname value
	 */
	public void setLastname (java.lang.String _lastname) {
		this._lastname = _lastname;
	}


	/**
	 * Return the value associated with the column: age
	 */
	public java.lang.Integer getAge () {
		return _age;
	}

	/**
	 * Set the value related to the column: age
	 * @param _age the age value
	 */
	public void setAge (java.lang.Integer _age) {
		this._age = _age;
	}


	/**
	 * Return the value associated with the column: books
	 */
	public java.util.Collection getBooks () {
		return this._books;
	}

	/**
	 * Set the value related to the column: books
	 * @param _books the books value
	 */
	public void setBooks (java.util.Collection _books) {
		this._books = _books;
	}
	
	public void addToBooks (Object obj) {
		if (null == this._books) this._books = new java.util.ArrayList();
		this._books.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.company.vo.base.BaseCustomer)) return false;
		else {
			com.company.vo.base.BaseCustomer mObj = (com.company.vo.base.BaseCustomer) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}